In [1]:
import pandas as pd

## Breast Cancer Dataset

In [2]:
cancer_train_path = "../data/breast_train.csv"
cancer_test_path = "../data/breast_test.csv"

In [24]:
df_cancer_train = pd.read_csv(cancer_train_path)
df_cancer_test = pd.read_csv(cancer_test_path)

In [25]:
df_cancer_train.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'class', 'age', 'menopause', 'tumor-size',
       'inv-nodes', 'node-caps', 'deg-malig', 'breast', 'breast-quad',
       'irradiat'],
      dtype='object')

In [26]:
df_cancer_test.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'class', 'age', 'menopause', 'tumor-size',
       'inv-nodes', 'node-caps', 'deg-malig', 'breast', 'breast-quad',
       'irradiat'],
      dtype='object')

In [27]:
df_cancer_train = df_cancer_train.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])

In [28]:
df_cancer_test = df_cancer_test.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])

In [29]:
len(df_cancer_test)

57

In [30]:
df_cancer_test.head()

,class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,0.0,3.0,2.0,4.0,0.0,1.0,1.0,0.0,2.0,0.0
1,0.0,4.0,0.0,3.0,0.0,1.0,0.0,0.0,2.0,0.0
2,0.0,3.0,0.0,4.0,0.0,1.0,1.0,0.0,2.0,0.0
3,0.0,2.0,2.0,2.0,0.0,1.0,1.0,0.0,2.0,0.0
4,0.0,3.0,0.0,7.0,0.0,1.0,1.0,0.0,2.0,0.0

In [31]:
len(df_cancer_train), len(df_cancer_test)

(228, 57)

In [33]:
# save
train_path = cancer_train_path.split("/")[-1]
test_path = cancer_test_path.split("/")[-1]

print(train_path, test_path)

breast_train.csv breast_test.csv

In [35]:
df_cancer_train.to_csv(train_path, index=False)

In [36]:
df_cancer_test.to_csv(test_path, index=False)

# COMPAS Dataset

In [15]:
compas_train_path = "../data/compas_train.csv"
compas_test_path = "../data/compas_test.csv"

In [16]:
df_compas_train = pd.read_csv(compas_train_path)
df_compas_test = pd.read_csv(compas_test_path)

In [17]:
df_compas_train = df_compas_train.drop(columns=['Unnamed: 0'])
df_compas_test = df_compas_test.drop(columns=['Unnamed: 0'])

KeyError: "['Unnamed: 0'] not found in axis"

In [18]:
df_compas_train.head()

   jfel  jmis  jot  pri  gender  age  charge  Race  two_year_recid
0   0.0   0.0  0.0  1.0     0.0  1.0     0.0   0.0               1
1   0.0   0.0  0.0  1.0     0.0  1.0     0.0   0.0               0
2   0.0   0.0  0.0  1.0     0.0  1.0     0.0   0.0               0
3   0.0   1.0  1.0  1.0     0.0  0.0     0.0   0.0               1
4   0.0   0.0  0.0  0.0     0.0  1.0     0.0   0.0               0

In [19]:
df_compas_test.head()

   jfel  jmis  jot  pri  gender  age  charge  Race  two_year_recid
0   0.0   0.0  0.0  1.0     0.0  0.0     0.0   0.0               1
1   0.0   0.0  0.0  0.0     0.0  1.0     0.0   1.0               0
2   0.0   0.0  0.0  1.0     0.0  2.0     0.0   0.0               1
3   0.0   0.0  1.0  1.0     0.0  0.0     0.0   0.0               1
4   0.0   0.0  0.0  0.0     0.0  1.0     0.0   0.0               1

In [13]:
df_compas_train.to_csv(compas_train_path, index=False)

In [14]:
df_compas_test.to_csv(compas_test_path, index=False)

# Diabetes dataset

In [22]:
diabetes_path = "../data/diabetes.csv"

In [26]:
db = pd.read_csv(diabetes_path)

In [27]:
db

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [28]:
db.value_counts()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI   DiabetesPedigreeFunction  Age  Outcome
0            57       60             0              0        21.7  0.735                     67   0          1
             67       76             0              0        45.3  0.194                     46   0          1
             73       0              0              0        21.1  0.342                     25   0          1
             74       52             10             36       27.8  0.269                     22   0          1
             78       88             29             40       36.9  0.434                     21   0          1
                                                                                                            ..
13           158      114            0              0        42.3  0.257                     44   1          1
14           100      78             25             184      36.6  0.412                     46   1          1
             175      62             30             0        33.6  0.212                     38   1          1
15           136      70             32             110      37.1  0.153                     43   1          1
17           163      72             41             114      40.9  0.817                     47   1          1
Name: count, Length: 768, dtype: int64

In [29]:
db.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [30]:
for c in ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']:
    print(c)
    db[c] = pd.qcut(db[c].values, 5, duplicates = 'drop').codes + 1

    print('************')

Pregnancies
************
Glucose
************
BloodPressure
************
SkinThickness
************
Insulin
************
BMI
************
DiabetesPedigreeFunction
************
Age
************

In [31]:
domain_db = {}
for c in db.columns:
    print(c)
    print(len(db[c].value_counts()))
    domain_db[c] = len(db[c].value_counts())
    print('************')

Pregnancies
5
************
Glucose
5
************
BloodPressure
5
************
SkinThickness
4
************
Insulin
3
************
BMI
5
************
DiabetesPedigreeFunction
5
************
Age
5
************
Outcome
2
************

In [32]:
domain_db

{'Pregnancies': 5,
 'Glucose': 5,
 'BloodPressure': 5,
 'SkinThickness': 4,
 'Insulin': 3,
 'BMI': 5,
 'DiabetesPedigreeFunction': 5,
 'Age': 5,
 'Outcome': 2}

In [33]:
len(db)

768

In [34]:
train_db = db.sample(n=(round(0.8*len(db))))
test_db = db[~db.index.isin(train_db.index)]

In [36]:
train_db.to_csv('diabetes_train.csv', index=False)
test_db.to_csv('diabetes_test.csv', index=False)